export const resourceSchema = {
  Category: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      picture: ['string', 'null'],
      description: { type: 'string' },
      categoryName: { type: 'string' },
    },
    required: ['description', 'categoryName'],
  },
  Customer: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      name: { type: 'string' },
      email: { type: 'string' },
    },
    required: ['name', 'email'],
  },
  Employee: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      city: { type: 'string' },
      email: { type: ['string', 'null'] },
      mgrId: { type: 'number' },
      notes: { type: ['string', 'null'] },
      phone: { type: 'string' },
      photo: { type: ['string', 'null'] },
      title: { type: 'string' },
      mobile: { type: ['string', 'null'] },
      region: { type: 'string' },
      address: { type: 'string' },
      country: { type: 'string' },
      hireDate: { type: 'string', format: 'date-time' },
      lastName: { type: 'string' },
      birthDate: { type: 'string', format: 'date-time' },
      extension: { type: ['string', 'null'] },
      firstName: { type: 'string' },
      photoPath: { type: ['string', 'null'] },
      postalCode: { type: 'string' },
      titleOfCourtesy: { type: 'string' },
    },
    required: ['firstName', 'lastName', 'phone', 'city'],
  },
  EmployeeTerritory: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      territoryCode: { type: 'string' },
      employeeId: { type: 'string' },
    },
  },
  OrderDetail: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      orderId: { type: 'number' },
      productId: { type: 'number' },
      discount: { type: 'number' },
      quantity: { type: 'number' },
      unitPrice: { type: 'number' },
    },
  },
  Product: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      unitPrice: { type: 'number' },
      categoryId: { type: 'number' },
      supplierId: { type: 'number' },
      productName: { type: 'string' },
      discontinued: { type: 'string' },
      reorderLevel: { type: ['string', 'null'] },
      unitsInStock: { type: ['string', 'null'] },
      unitsOnOrder: { type: ['string', 'null'] },
      quantityPerOrder: { type: ['string', 'null'] },
    },
  },
  Region: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      regionDescription: { type: 'string' },
    },
  },
  SalesOrder: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      freight: { type: 'number' },
      shipCity: { type: 'string' },
      shipName: { type: 'string' },
      orderDate: { type: 'string', format: 'date-time' },
      shipperId: { type: 'number' },
      customerId: { type: 'number' },
      employeeId: { type: 'number' },
      shipRegion: { type: ['string', 'null'] },
      shipAddress: { type: 'string' },
      shipCountry: { type: 'string' },
      shippedDate: { type: 'string', format: 'date-time' },
      requiredDate: { type: 'string', format: 'date-time' },
      shipPostalCode: { type: 'string' },
    },
  },
  Shipper: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      phone: { type: 'string' },
      companyName: { type: 'string' },
    },
  },
  Supplier: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      fax: { type: ['string', 'null'] },
      city: { type: 'string' },
      email: { type: ['string', 'null'] },
      phone: { type: 'string' },
      region: { type: ['string', 'null'] },
      address: { type: 'string' },
      country: { type: 'string' },
      HomePage: { type: ['string', 'null'] },
      postalCode: { type: 'string' },
      companyName: { type: 'string' },
      contactName: { type: 'string' },
      contactTitle: { type: 'string' },
    },
  },
  Territory: {
    type: 'object',
    properties: {
      id: { type: 'number' },
      url: { type: 'string' },
      regionId: { type: 'number' },
      territoryCode: { type: 'string' },
      territorydescription: { type: 'string' },
    },
  },
}
